name: Push

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '10.x'

jobs:
   build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm install
        npm run build
    - name: push
      uses: izyhang/SFTP-Deploy-Action@v1.1
      with:
        username: 'root'
        server: '${{ secrets.SSH_IP }}'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './dist/*'
        remote_path: '/home/zyhang/project/pass_gen/public/'
